name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for raising an issue to API-bot! 😊 Please wait for the maintainers to come and review it."
        pr-message: "Thanks for raising a PR to API-bot! 😊 Please wait for the maintainers to come and review it."
